export type ProviderCapability = "embedding" | "chat" | "ocr" | "rerank";

export interface ProviderPreset {
  id: string;
  label: string;
  url: string;
  meta: string;
  aliases: string[];
  capabilities: ProviderCapability[];
}

const all: ProviderCapability[] = ["embedding", "chat", "ocr", "rerank"];
const chatVision: ProviderCapability[] = ["chat", "ocr"];
const chatEmbeddingVision: ProviderCapability[] = ["embedding", "chat", "ocr"];

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    id: "siliconflow-cn",
    label: "SiliconFlow（中国大陆）",
    url: "https://api.siliconflow.cn/v1",
    meta: "按量计费 · cn",
    aliases: ["硅基流动", "silicon flow", "china", "mainland", "国内"],
    capabilities: all,
  },
  {
    id: "siliconflow-global",
    label: "SiliconFlow（海外）",
    url: "https://api-st.siliconflow.cn/v1",
    meta: "按量计费 · global",
    aliases: ["硅基流动", "silicon flow", "international", "global", "海外"],
    capabilities: all,
  },
  {
    id: "aihubmix",
    label: "AIHubMix（10% 优惠）",
    url: "https://aihubmix.com/v1",
    meta: "聚合平台 · APP-Code 自动附加",
    aliases: ["ai hub mix", "聚合", "折扣", "优惠", "gateway"],
    capabilities: all,
  },
  {
    id: "aihubmix-api",
    label: "AIHubMix（10% 优惠·备用域名）",
    url: "https://api.aihubmix.com/v1",
    meta: "聚合平台 · APP-Code 自动附加",
    aliases: ["ai hub mix", "聚合", "备用", "折扣", "优惠"],
    capabilities: all,
  },
  {
    id: "openai",
    label: "OpenAI（全球）",
    url: "https://api.openai.com/v1",
    meta: "按量计费 · global",
    aliases: ["chatgpt", "gpt", "o1", "o3", "o4"],
    capabilities: chatEmbeddingVision,
  },
  {
    id: "openrouter",
    label: "OpenRouter（全球）",
    url: "https://openrouter.ai/api/v1",
    meta: "聚合平台 · 按量计费",
    aliases: ["open router", "聚合", "global"],
    capabilities: chatVision,
  },
  {
    id: "anthropic",
    label: "Claude / Anthropic（全球）",
    url: "https://api.anthropic.com/v1",
    meta: "按量计费 · OpenAI 兼容层",
    aliases: ["claude", "anthropic", "sonnet", "opus", "haiku"],
    capabilities: chatVision,
  },
  {
    id: "deepseek",
    label: "DeepSeek（官方）",
    url: "https://api.deepseek.com",
    meta: "按量计费 · cn/global",
    aliases: ["深度求索", "deep seek", "deepseek chat", "deepseek reasoner"],
    capabilities: ["chat"],
  },
  {
    id: "xiaomi-mimo-payg",
    label: "Xiaomi MiMo（按量付费）",
    url: "https://api.xiaomimimo.com/v1",
    meta: "sk-* · global",
    aliases: ["小米", "mimo", "pay as you go", "payg", "按量", "sk"],
    capabilities: chatVision,
  },
  {
    id: "xiaomi-mimo-token-plan-cn",
    label: "Xiaomi MiMo Token Plan（cn）",
    url: "https://token-plan-cn.xiaomimimo.com/v1",
    meta: "tp-* · 中国集群 · 编程工具限定",
    aliases: ["小米", "mimo", "tokenplan", "token plan", "套餐", "中国"],
    capabilities: chatVision,
  },
  {
    id: "xiaomi-mimo-token-plan-sgp",
    label: "Xiaomi MiMo Token Plan（sgp）",
    url: "https://token-plan-sgp.xiaomimimo.com/v1",
    meta: "tp-* · 新加坡集群 · 编程工具限定",
    aliases: ["小米", "mimo", "tokenplan", "token plan", "套餐", "singapore", "新加坡"],
    capabilities: chatVision,
  },
  {
    id: "xiaomi-mimo-token-plan-ams",
    label: "Xiaomi MiMo Token Plan（ams）",
    url: "https://token-plan-ams.xiaomimimo.com/v1",
    meta: "tp-* · 欧洲集群 · 编程工具限定",
    aliases: ["小米", "mimo", "tokenplan", "token plan", "套餐", "europe", "欧洲", "amsterdam"],
    capabilities: chatVision,
  },
  {
    id: "kimi-platform",
    label: "Kimi / Moonshot（按量付费·cn）",
    url: "https://api.moonshot.cn/v1",
    meta: "Kimi 开放平台 · 按量计费",
    aliases: ["月之暗面", "moonshot", "kimi open platform", "中国"],
    capabilities: chatVision,
  },
  {
    id: "kimi-code",
    label: "Kimi Code（订阅·global）",
    url: "https://api.kimi.com/coding/v1",
    meta: "会员订阅 · 编程工具限定",
    aliases: ["月之暗面", "moonshot", "coding", "membership", "会员"],
    capabilities: ["chat"],
  },
  {
    id: "google-gemini",
    label: "Google Gemini（全球）",
    url: "https://generativelanguage.googleapis.com/v1beta/openai",
    meta: "按量计费 · OpenAI 兼容",
    aliases: ["google ai", "gemini", "谷歌", "ai studio"],
    capabilities: chatEmbeddingVision,
  },
  {
    id: "dashscope-cn",
    label: "阿里云百炼 / DashScope（cn）",
    url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    meta: "按量计费 · 中国大陆",
    aliases: ["阿里云", "百炼", "通义千问", "qwen", "dash scope", "china"],
    capabilities: chatEmbeddingVision,
  },
  {
    id: "dashscope-sgp",
    label: "阿里云百炼 / DashScope（sgp）",
    url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    meta: "按量计费 · 新加坡",
    aliases: ["阿里云", "百炼", "通义千问", "qwen", "dash scope", "international", "singapore"],
    capabilities: chatEmbeddingVision,
  },
  {
    id: "zhipu",
    label: "智谱 BigModel（cn）",
    url: "https://open.bigmodel.cn/api/paas/v4",
    meta: "按量计费 · 中国大陆",
    aliases: ["智谱", "glm", "chatglm", "big model", "zhipu"],
    capabilities: chatEmbeddingVision,
  },
  {
    id: "baidu-qianfan",
    label: "百度智能云千帆（cn）",
    url: "https://qianfan.baidubce.com/v2",
    meta: "按量计费 · 中国大陆",
    aliases: ["百度", "千帆", "文心", "ernie", "baidu"],
    capabilities: chatEmbeddingVision,
  },
  {
    id: "tencent-hunyuan",
    label: "腾讯混元（cn）",
    url: "https://api.hunyuan.cloud.tencent.com/v1",
    meta: "按量计费 · 中国大陆",
    aliases: ["腾讯", "混元", "hunyuan", "tencent"],
    capabilities: chatVision,
  },
  {
    id: "volcengine-ark",
    label: "火山引擎方舟（cn）",
    url: "https://ark.cn-beijing.volces.com/api/v3",
    meta: "按量计费 · 北京",
    aliases: ["火山引擎", "方舟", "豆包", "doubao", "volcengine", "ark"],
    capabilities: chatVision,
  },
  {
    id: "byteplus-modelark",
    label: "BytePlus ModelArk（sgp）",
    url: "https://ark.ap-southeast-1.bytepluses.com/api/v3",
    meta: "按量计费 · 新加坡",
    aliases: ["byte plus", "字节", "model ark", "singapore"],
    capabilities: chatVision,
  },
  {
    id: "modelscope",
    label: "魔搭 ModelScope（cn）",
    url: "https://api-inference.modelscope.cn/v1",
    meta: "按量 / 免费额度 · 中国大陆",
    aliases: ["魔搭", "model scope", "阿里", "中国"],
    capabilities: chatEmbeddingVision,
  },
  {
    id: "groq",
    label: "GroqCloud（全球）",
    url: "https://api.groq.com/openai/v1",
    meta: "按量 / 免费额度 · global",
    aliases: ["groq", "lpu", "global"],
    capabilities: chatVision,
  },
  {
    id: "together",
    label: "Together AI（全球）",
    url: "https://api.together.xyz/v1",
    meta: "按量计费 · global",
    aliases: ["togetherai", "together xyz", "global"],
    capabilities: all,
  },
  {
    id: "fireworks",
    label: "Fireworks AI（全球）",
    url: "https://api.fireworks.ai/inference/v1",
    meta: "按量计费 · global",
    aliases: ["fireworksai", "fireworks ai", "global"],
    capabilities: chatEmbeddingVision,
  },
  {
    id: "mistral",
    label: "Mistral AI（欧洲）",
    url: "https://api.mistral.ai/v1",
    meta: "按量计费 · eu",
    aliases: ["mistral", "codestral", "europe", "欧洲"],
    capabilities: chatEmbeddingVision,
  },
  {
    id: "xai",
    label: "xAI / Grok（全球）",
    url: "https://api.x.ai/v1",
    meta: "按量计费 · global",
    aliases: ["x ai", "grok", "twitter", "global"],
    capabilities: chatVision,
  },
  {
    id: "nvidia-nim",
    label: "NVIDIA NIM（全球）",
    url: "https://integrate.api.nvidia.com/v1",
    meta: "按量 / 免费额度 · global",
    aliases: ["英伟达", "nvidia", "nim", "build nvidia"],
    capabilities: chatEmbeddingVision,
  },
  {
    id: "cerebras",
    label: "Cerebras Inference（全球）",
    url: "https://api.cerebras.ai/v1",
    meta: "按量 / 免费额度 · global",
    aliases: ["cerebras", "wafer scale", "global"],
    capabilities: ["chat"],
  },
  {
    id: "jina",
    label: "Jina AI（全球）",
    url: "https://api.jina.ai/v1",
    meta: "Embedding / Reranker · global",
    aliases: ["jina", "向量", "重排", "embedding", "reranker"],
    capabilities: ["embedding", "rerank"],
  },
  {
    id: "cohere",
    label: "Cohere Rerank（全球）",
    url: "https://api.cohere.com/v2",
    meta: "Reranker · global",
    aliases: ["cohere", "重排", "reranker"],
    capabilities: ["rerank"],
  },
];

export function providerPresetsFor(capability: ProviderCapability): ProviderPreset[] {
  return PROVIDER_PRESETS.filter((provider) => provider.capabilities.includes(capability));
}
